name: Deploy production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/demo
            git pull
            npm install
            node ace build
            mv -f build ../build
            mv -f .env ../build/.env
            cd ../build
            npm install
            mkdir tmp
            chmod 777 tmp
            node ace configure easeadmin --force
            node ace migration:run
            node ace db:seed
            pm2 stop node /var/www/build/bin/server.js
            pm2 start node /var/www/build/bin/server.js
            pm2 stop node /var/www/build/bin/console.js
            pm2 start node /var/www/build/bin/console.js